feat(cronjobs): add monitor to all cronjobs

diff --git a/kube/services/jobs/google-verify-bucket-access-group-cronjob.yaml b/kube/services/jobs/google-verify-bucket-access-group-cronjob.yaml
--- a/kube/services/jobs/google-verify-bucket-access-group-cronjob.yaml
+++ b/kube/services/jobs/google-verify-bucket-access-group-cronjob.yaml
@@ -39,9 +39,11 @@ spec:
             - name: config-helper
               configMap:
                 name: config-helper
-          containers:
+            - name: shared-data
+              emptyDir: {}
+          initContainers:
           - name: fence
-            image: quay.io/cdis/fence:master
+            GEN3_FENCE_IMAGE
             imagePullPolicy: Always
             env:
               - name: PYTHONPATH
@@ -74,6 +76,8 @@ spec:
                 readOnly: true
                 mountPath: "/var/www/fence/config_helper.py"
                 subPath: config_helper.py
+              - name: shared-data
+                mountPath: /mnt/shared
             command: ["/bin/bash"]
             args:
               - "-c"
@@ -81,5 +85,39 @@ spec:
                 fence-create bucket-access-group-verify
                 if [[ $? != 0 ]]; then
                   echo "WARNING: non zero exit code: $?"
+                else
+                  touch /mnt/shared/success
+                fi
+          containers:
+          - name: awshelper
+            env:
+              - name: slackWebHook
+                valueFrom:
+                    configMapKeyRef:
+                      name: global
+                      key: slack_webhook
+              - name: gen3Env
+                valueFrom:
+                    configMapKeyRef:
+                      name: global
+                      key: environment
+            image: quay.io/cdis/awshelper:master
+            volumeMounts:
+              - name: shared-data
+                mountPath: /mnt/shared
+            command: ["/bin/bash"]
+            args:
+              - "-c"
+              - |
+                if ! [ -f /mnt/shared/success ]; then
+                  # AZ=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
+                  # RE=${AZ::-1}
+                  # aws --region ${RE} sns publish --message "google-verify-bucket-access-group failed for ${gen3Env}" --topic-arn <TOPIC ARN>
+                  curl -X POST --data-urlencode "payload={\"text\": \"AWSHelper: google-verify-bucket-access-group failed for ${gen3Env} \"}" "${slackWebHook}"
+                else
+                  HOUR=$(TZ='America/Chicago' date "+%H")
+                  if [ ${HOUR} -eq 09 ]; then
+                    curl -X POST --data-urlencode "payload={\"text\": \"AWSHelper: google-verify-bucket-access-group succeeded for ${gen3Env} \"}" "${slackWebHook}"
+                  fi
                 fi
           restartPolicy: Never
