Chore/cron exit code (#1205)
* chore(cron): etl,usersync exit codes

* chore(presigned-url): fence 2.7.1 launch support

diff --git a/kube/services/jobs/usersync-cronjob.yaml b/kube/services/jobs/usersync-cronjob.yaml
--- a/kube/services/jobs/usersync-cronjob.yaml
+++ b/kube/services/jobs/usersync-cronjob.yaml
@@ -9,7 +9,7 @@ spec:
   failedJobsHistoryLimit: 2
   jobTemplate:
     spec:
-      # not yet supported - backOffLimit: 3
+      backoffLimit: 0
       template:
         metadata:
           labels:
@@ -177,6 +177,7 @@ spec:
                     fi
                   else
                     echo "/mnt/shared/user.yaml did not appear within timeout :-("
+                    false  # non-zero exit code
                   fi
                   exitcode=$?
                 else
@@ -209,6 +210,7 @@ spec:
                   fi
                 fi
                 echo "Exit code: $exitcode"
+                exit "$exitcode"
 
           - name: awshelper
             image: quay.io/cdis/awshelper:master
@@ -236,6 +238,7 @@ spec:
                     n=$[$n+1]
                     sleep 2
                   done
+                  exitcode=0
                   if [[ -f /mnt/shared/user.yaml ]]; then
                     echo "awshelper container user.yaml diff ..."
                     diff /var/www/fence/user.yaml /mnt/shared/user.yaml
@@ -249,9 +252,12 @@ spec:
                     else
                       echo "no difference found"
                     fi
+                  else
+                    exitcode=1
                   fi
                 fi
-                echo "Helper exit code: $?"
+                echo "Helper exit code: $exitcode"
+                exit "$exitcode"
             env:
               - name: userYamlS3Path
                 valueFrom:
